### ISSUE TITLE
post script not working in orcaslicer

### ISSUE THREAD

**Issue by wolverine969** [macdylan/SMFix#3]
Hi,

I'm using orcaslicer with my snapmaker a350. For some reason I'm unable to use your post script on for my Snapmaker A350 due to the error below. Could you please advise what I could be doing wrong.

I ran the smfix-win64 file and then inputted /path/to/smfix into the post processing field within orcaslicer.

![image](https://github.com/macdylan/SMFix/assets/48618205/1b431f91-9b86-4916-a4eb-92ebf46c687c)

![image](https://github.com/macdylan/SMFix/assets/48618205/91742ccb-b0d8-417c-b204-855b527290ba)

**Comment by macdylan** [comment]
Assuming path in your computer is d:\smfix\smfix-win64.exe, replace /path/to/smfix with that.

**Comment by wolverine969** [comment]
Hi,This is the path where I extracted the file to. What would the post processing location be?This is the location of orca slicerRegardsVireshSent from my iPhoneOn 27 Aug 2023, at 10:20 am, Dylan ***@***.***> wrote:﻿
Assuming path in your computer is d:\smfix\smfix-win64.exe replace it with /path/to/smfix
